#!/usr/bin/env python

import os
import json
from ed_helper_publisher.utilities import print_json

terraform_state_file = os.environ.get("TERRAFORM_STATE_FILE","terraform.tfstate")

with open(terraform_state_file) as json_file:
    data = json.load(json_file)

for resource in data["resources"]:
    for instance in resource["instances"]:
        _type = resource["type"]
        # this is the main category for the terraform template
        if _type != "aws_subnet": continue

        results = {}
        for _key,_value in resource["instances"][0]["attributes"].iteritems():
            results[_key] = _value

        results["name"] = results["tags"]["Name"]
        results["tags"] = [ results["tags"]["Name"] ]
        results["_id"] = results["id"]

results["raw"] = {}
results["raw"]["terraform"] = data
results["provider"] = "aws"
results["resource_type"] = "subnet"
if os.environ.get("AWS_DEFAULT_REGION"): results["region"] = os.environ["AWS_DEFAULT_REGION"]
if os.environ.get("VPC_NAME"): 
    results["vpc_name"] = os.environ["VPC_NAME"]
    results["vpc"] = os.environ["VPC_NAME"]

print '_ed_begin_output'
print_json(results)
print '_ed_end_output'
