#!/usr/bin/env python
#
#This file is part of "jiffy".
#
#Project: jiffy: A product for building and managing infrastructure: 
#cloud provider services, and servers and their configurations.
#
#Description: A product for building and managing infrastructure. 
#This includes third party API calls for services such as virtual
#cloud servers, load balancers, databases, and other. The product 
#manages connectivity and appropriate communication among these 
#aws.
#
#Copyright (C) Gary Leong - All Rights Reserved
#Unauthorized copying of this file, via any medium is strictly prohibited
#Proprietary and confidential
#Written by Gary Leong  <gwleong@gmail.com, September 17,2015

import os
import json
import sys
from time import sleep

from ed_helper_publisher.loggerly import ElasticDevLogger
from ed_helper_publisher.cloud.awscli import AwsCli
from ed_helper_publisher.utilities import convert_str2json

class Main(AwsCli):

    def __init__(self,**kwargs):

        AwsCli.__init__(self)
        self.classname = 'APIgateway'
        self.logger = ElasticDevLogger(self.classname,logcategory="cloudprovider")
        self.logger.debug("Instantiating %s" % self.classname)
        self.resource_type = "alb"
        self.base_cmd = "aws elbv2"

    def _get_app_lb_by_arn(self,**kwargs):

        convert_to_json = kwargs.get("convert_to_json",True)

        cmd = "aws elbv2 describe-load-balancers --load-balancer-arns {} --region {}".format(kwargs["arn"],self.aws_default_region)

        try:
            output = self.execute(cmd,convert_to_json=convert_to_json).get("output")["LoadBalancers"][0]
        except:
            output = None
 
        return output
    
    def _get_all_app_lbs(self,**kwargs):

        cmd = "aws elbv2 describe-load-balancers --region {}".format(self.aws_default_region)

        try:
            output = self.execute(cmd,convert_to_json=True).get("output")["LoadBalancers"]
        except:
            output = None
    
        return output

    def _get_tags_on_app_lb(self,**kwargs):

        cmd = "aws elbv2 describe-tags --resource-arns {} --region {}".format(kwargs["arn"],self.aws_default_region)

        tags = self.execute(cmd,convert_to_json=True,exit_error=True)["output"]["TagDescriptions"]["Tags"]

        for tag in tags:
            if tag["Key"] != "name": continue
            if tag["Value"] == kwargs["name"]: return tags

    def _get_app_lb_by_name(self,**kwargs):

        output = self._get_all_app_lbs(**kwargs)
        if not output: return

        for item in output:
            #arn = item["LoadBalancerArn"]
            #if not self._get_tags_on_app_lb(arn=arn,name=kwargs["name"]): continue
            if kwargs["name"] != item["LoadBalancerName"]: continue
            return item

    def exists(self,**kwargs):

        name = kwargs.get("name")
        arn = kwargs.get("arn")

        results = {"status":True}

        if arn:
            output = self._get_app_lb_by_arn(**kwargs)

            if output: 
                results["output"] = output
                return results

        elif name:
            output = self._get_app_lb_by_name(**kwargs)

            if output: 
                results["output"] = output
                return results
        elif not name or not arn:
            output = self._get_all_app_lbs(**kwargs)

            if not output:
                results["output"] = []
                return results

        # It fails if it gets to here.
        results["status"] = False
        results["output"] = output
        failed_message = "Finding existing item(s) failed"
        failed_message = 'Could not find item name = "{}" arn "{}"'.format(name,arn)
        results["failed_message"] = failed_message
        return results

    def get(self):

        results = self.exists(**self.inputargs)

        if results.get("status") is None: exit(0)

        if results.get("status") is False: 
            self.cmd_failed(**self.inputargs)

        self.successful_output(output=results)

    def _get_file_config(self):

        #{
        #  "Name": "%name%s",
        #  "Subnets": [
        #    "%publicSubnet1%",
        #    "%publicSubnet2%"
        #  ],
        #  "SecurityGroups": [
        #    "%loadBalancerSecurityGroup%"
        #  ],
        #  "Scheme": "internet-facing",
        #  "Tags": [
        #    {
        #      "Key": "Name",
        #      "Value": "myEC2Workshop"
        #    }
        #  ],
        #  "Type": "application"
        #}

        name = self.inputargs["name"]
        subnets = self.inputargs.get("subnets")
        security_groups = self.inputargs.get("security_groups")

        if not subnets:
            msg = "At least 2 subnets from two different available zones are required"
            self.logger.error(msg)
            exit(4)

        if not security_groups:
            msg = "One security group is required"
            self.logger.error(msg)
            exit(4)

        # Name of ALB
        self.file_config = {"Name":name}
        self.file_config["Scheme"] = "internet-facing"
        self.file_config["Type"] = "application"
        self.file_config["Tags"] = [ {"Key":"name","Value":name} ]

        # Security Groups
        self.file_config["SecurityGroups"] = [ security_groups ]

        # Subnets
        self.file_config["Subnets"] = convert_str2json(subnets)

        return self.file_config
  
    def create(self):

        name = self.inputargs["name"]
        subnets = self.inputargs.get("subnets")
        security_groups = self.inputargs.get("security_groups")

        # Needs False if it finds it
        if self.exists(convert_to_json=False,**self.inputargs).get("status") is not False:
            failed_message = "load balancer name = {} already exists".format(name)
            self.cmd_failed(failed_message=failed_message)

        self.set_ondisktmp()
        self._get_file_config()
        self.file_config_loc = os.path.join(self.tempdir.get(),name)
        self.write_file_config()

        cmd = "{} create-load-balancer --cli-input-json file://{} --region {}".format(self.base_cmd,self.file_config_loc,self.aws_default_region)
        _output = self.execute(cmd,convert_to_json=True,exit_error=True).get("output")
        self.tempdir.delete()
        output = convert_str2json(_output)["LoadBalancers"][0]

        # Validate load balancer has been created
        exists = self.exists(arn=output["LoadBalancerArn"],**self.inputargs)["output"]

        dns_name = exists["DNSName"]
        vpc_id = exists["VpcId"]
        arn = exists["LoadBalancerArn"]

        resource = {"raw":{}}
        resource["raw"]["app_lb"] = exists
        resource["_id"] = arn
        resource["id"] = arn
        resource["name"] = name
        resource["resource_type"] = self.resource_type
        resource["provider"] = "ec2"
        resource["dns_name"] = dns_name
        resource["region"] = self.aws_default_region
        resource["aws_default_region"] = self.aws_default_region
        resource["tags"] = [ self.aws_default_region, self.resource_type, "app_lb", "loadbalancer", "ec2", vpc_id, dns_name, name, arn ]
        resource["subnets"] = subnets
        resource["security_groups"] = security_groups
        resource["security_groups_ids"] = security_groups
        resource["security-groups-ids"] = security_groups
        resource["sg_ids"] = security_groups
        resource["vpc_id"] = vpc_id

        resource["destroy"] = {"shelloutconfig":"elasticdev:::aws::alb"}
        resource["destroy"]["insert_env_vars"] = json.dumps(["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"])
        resource["destroy"]["env_vars"] = json.dumps({"ARN":arn,"METHOD":"destroy","AWS_DEFAULT_REGION":self.aws_default_region})

        self.successful_output(output=resource)

    def destroy(self):

        self.logger.debug('Looking to destroy loadbalancer name = "{}" arn "{}" in "{}"'.format(self.inputargs.get("name"),
                                                                                                self.inputargs.get("arn"),
                                                                                                self.aws_default_region))

        _results = self.exists(convert_to_json=False,**self.inputargs)

        if not _results.get("status"):
            output = 'loadbalancer name = "{}" arn "{}" in "{}" does not exists'.format(self.inputargs.get("name"),
                                                                                        self.inputargs.get("arn"),
                                                                                        self.aws_default_region)
            self.successful_output(output=output)

        arn = _results["output"].get("LoadBalancerArn")

        if not arn:
            failed_message = "Cannot determine cloud arn to delete"
            self.cmd_failed(failed_message=failed_message)

        cmd = "aws elbv2 delete-load-balancer --load-balancer-arn {} --region {}".format(arn,self.aws_default_region)

        for retry in range(0,3):
            results = self.execute(cmd,convert_to_json=None)
            if results.get("status") is True: 
                self.logger.debug('loadbalancer arn "{}" deleted'.format(arn))
                self.successful_output(output=results["output"])
            sleep(1)

        failed_message = "could not delete loadbalancer arn {} in {}".format(arn,self.aws_default_region)
        self.cmd_failed(failed_message=failed_message)

def usage():

    print """

script + environmental variables

or

script + json_input (as argument)

environmental variables:
    basic:
        AWS_ACCESS_KEY_ID  
        AWS_SECRET_ACCESS_KEY
        METHOD (create/get/destroy)
        AWS_DEFAULT_REGION (optional)

    create:
        NAME
        SUBNETS (at least 2 available zones)
        SECURITY_GROUPS 

    destroy:
        ARN or NAME

    get:
        ARN (optional)
        NAME (optional)

       """
    exit(4)

if __name__ == '__main__':

    try:
        json_input = sys.argv[1]
    except:
        json_input = None

    main = Main()

    if json_input:
        main.set_inputargs(json_input=json_input)
    else:
        set_env_vars = [ "method",
                         "name",
                         "aws_default_region",
                         "arn",
                         "security_groups",
                         "subnets" ]

        main.set_inputargs(set_env_vars=set_env_vars)
   
    method = main.inputargs.get("method")

    if not method:
        print "method/ENV VARIABLE METHOD is needed"
        exit(4)

    # Set class and region
    main.get_region()

    if method == "create":

        main.check_required_inputargs(keys=["name"])
        main.create()

    elif method == "destroy":
    
        main.check_either_inputargs(keys=["name","arn"])
        main.destroy()

    elif method == "get":

        main.get()

    else:
        usage()
        print 'method "{}" not supported!'.format(method)
        exit(4)
