#!/usr/bin/env python
#
#This file is part of "jiffy".
#
#Project: jiffy: A product for building and managing infrastructure: 
#cloud provider services, and servers and their configurations.
#
#Description: A product for building and managing infrastructure. 
#This includes third party API calls for services such as virtual
#cloud servers, load balancers, databases, and other. The product 
#manages connectivity and appropriate communication among these 
#aws.
#
#Copyright (C) Gary Leong - All Rights Reserved
#Unauthorized copying of this file, via any medium is strictly prohibited
#Proprietary and confidential
#Written by Gary Leong  <gwleong@gmail.com, September 17,2015

import json
import sys

from ed_helper_publisher.loggerly import ElasticDevLogger
from ed_helper_publisher.cloud.awscli import AwsCli

class Main(AwsCli):

    def __init__(self,**kwargs):

        AwsCli.__init__(self)
        self.classname = 'APIgatewayCustom'
        self.logger = ElasticDevLogger(self.classname,logcategory="cloudprovider")
        self.logger.debug("Instantiating %s" % self.classname)

    def get(self):

        cmd = "aws apigateway get-domain-name --domain-name '{}'".format(self.inputargs["domain_name"])
        output = self.execute(cmd,convert_to_json=True,exit_error=True).get("output")
        self.successful_output(output=output)

    def create(self):

        domain_name = self.inputargs["domain_name"]
        arn = self.inputargs["arn"]
        endpoint_configuration = self.inputargs.get("endpoint_configuration")
        if not endpoint_configuration: endpoint_configuration = json.dumps({ "types": ["REGIONAL"] })

        cmd = "aws apigateway create-domain-name \
                   --domain-name '{}' \
                   --endpoint-configuration '{}' \
                   --regional-certificate-arn '{}'".format(domain_name,
                                                           endpoint_configuration,
                                                           arn)

        output = self.execute(cmd,convert_to_json=True,exit_error=True).get("output")
        if not isinstance(output,dict): output = json.loads(output)

        resource = {"raw":{}}
        resource["_id"] = self.get_hash("{}.{}.{}".format(domain_name,self.aws_default_region,arn))
        resource["raw"]["apigateway_custom_domain"] = output
        resource["domain_name"] = domain_name
        resource["arn"] = arn
        resource["resource_type"] = "apigateway_custom_domain"
        resource["provider"] = "aws"
        resource["region"] = self.aws_default_region
        resource["aws_default_region"] = self.aws_default_region
        resource["tags"] = [ self.aws_default_region, arn, "custom_domain" ]

        resource["destroy"] = {"shelloutconfig":"elasticdev:::aws::apigateway_custom_domain"}
        resource["destroy"]["insert_env_vars"] = json.dumps(["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"])
        resource["destroy"]["env_vars"] = json.dumps({"DOMAIN_NAME":domain_name,"METHOD":"destroy","AWS_DEFAULT_REGION":self.aws_default_region})

        self.successful_output(output=resource)

    def destroy(self):

        cmd = "aws apigateway delete-domain-name --domain-name '{}' --region {}".format(self.inputargs["domain_name"],self.aws_default_region)
        results = self.execute(cmd,convert_to_json=None,exit_error=False)
        self.successful_output(output=results)

def usage():

    print """
script + environmental variables

or

script + json_input (as argument)

environmental variables:
    basic:
        AWS_ACCESS_KEY_ID  
        AWS_SECRET_ACCESS_KEY
        METHOD
        AWS_DEFAULT_REGION (optional)

    create:
        DOMAIN_NAME
        ARN

    destroy:
        DOMAIN_NAME

    get:
        DOMAIN_NAME

       """
    exit(4)

if __name__ == '__main__':

    try:
        json_input = sys.argv[1]
    except:
        json_input = None

    main = Main()

    if json_input:
        main.set_inputargs(json_input=json_input)
    else:
        set_env_vars = [ "method",
                         "domain_name",
                         "aws_default_region",
                         "arn" ]

        main.set_inputargs(set_env_vars=set_env_vars)
   
    method = main.inputargs.get("method")

    if not method:
        print "method/ENV VARIABLE METHOD is needed"
        exit(4)

    # Set class and region
    main.get_region()

    if method == "create":

        main.check_required_inputargs(keys=["domain_name","arn"])
        main.create()

    elif method == "destroy":
    
        main.check_either_inputargs(keys=["domain_name"])
        main.destroy()

    elif method == "get":

        main.check_either_inputargs(keys=["domain_name"])
        main.get()

    else:
        usage()
        print 'method "{}" not supported!'.format(method)
        exit(4)
