#!/usr/bin/env python
#
#This file is part of "jiffy".
#
#Project: jiffy: A product for building and managing infrastructure: 
#cloud provider services, and servers and their configurations.
#
#Description: A product for building and managing infrastructure. 
#This includes third party API calls for services such as virtual
#cloud servers, load balancers, databases, and other. The product 
#manages connectivity and appropriate communication among these 
#aws.
#
#Copyright (C) Gary Leong - All Rights Reserved
#Unauthorized copying of this file, via any medium is strictly prohibited
#Proprietary and confidential
#Written by Gary Leong  <gwleong@gmail.com, September 17,2015

import json
import sys
from time import sleep

from ed_helper_publisher.loggerly import ElasticDevLogger
from ed_helper_publisher.cloud.awscli import AwsCli

class Main(AwsCli):

    def __init__(self,**kwargs):

        AwsCli.__init__(self)
        self.classname = 'APIgateway'
        self.logger = ElasticDevLogger(self.classname,logcategory="cloudprovider")
        self.logger.debug("Instantiating %s" % self.classname)

    def exists(self,**kwargs):

        name = kwargs.get("name")
        _id = kwargs.get("id")
        convert_to_json = kwargs.get("convert_to_json",True)

        results = {"status":True}

        cmd = "aws apigateway get-rest-apis --region {}".format(self.aws_default_region)
        output = self.execute(cmd,convert_to_json=convert_to_json).get("output")

        # No entries found
        if not output: 
            results["status"] = None
            results["output"] = []
            return results

        items = output["items"]

        # Return all entries
        if not name and not _id: 
            results["output"] = items
            return results

        # Return an entry with a specific name or id
        for item in items:
            if name and item["name"] != name: continue
            if _id and item["id"] != _id: continue
            results["output"] = item
            return results

        results["status"] = False
        results["output"] = output

        failed_message = "Finding existing item(s) failed"
        failed_message = 'Could not find item name = "{}" id "{}"'.format(name,_id)
        results["failed_message"] = failed_message

        return results

    def get(self):

        results = self.exists(**self.inputargs)

        if results.get("status") is None: exit(0)

        if results.get("status") is False: 
            self.cmd_failed(**self.inputargs)

        self.successful_output(output=results)

    def create(self):

        name = self.inputargs.get("name")
        description = self.inputargs.get("description",name)
        endpoint_configuration = self.inputargs.get("endpoint_configuration")
        if not endpoint_configuration: endpoint_configuration = json.dumps({ "types": ["REGIONAL"] })

        # Needs False if it finds the server
        if self.exists(convert_to_json=False,**self.inputargs).get("status") is not False:
            failed_message = "apigateway name = {} already exists".format(name)
            self.cmd_failed(failed_message=failed_message)

        cmd = "aws apigateway create-rest-api \
               --name '{}' \
               --description '{}' \
               --region '{}' \
               --endpoint-configuration '{}'".format(name,
                                                     description,
                                                     self.aws_default_region,
                                                     endpoint_configuration)

        output = self.execute(cmd,convert_to_json=True,exit_error=True).get("output")
        if not isinstance(output,dict): output = json.loads(output)

        resource = {"raw":{}}
        resource["raw"]["apigateway"] = output
        resource["_id"] = output["id"]
        resource["id"] = output["id"]
        resource["name"] = output["name"]
        resource["resource_type"] = "apigateway"
        resource["provider"] = "aws"
        resource["region"] = self.aws_default_region
        resource["aws_default_region"] = self.aws_default_region
        resource["tags"] = [ self.aws_default_region ]

        resource["destroy"] = {"shelloutconfig":"elasticdev:::aws::apigateway"}
        resource["destroy"]["insert_env_vars"] = json.dumps(["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"])
        resource["destroy"]["env_vars"] = json.dumps({"ID":output["id"],"METHOD":"destroy","AWS_DEFAULT_REGION":self.aws_default_region})
        #resource["destroy"]["json_args"] = json.dumps({"id":output["id"],"method":"destroy","region":self.aws_default_region})

        self.successful_output(output=resource)

    def destroy(self):

        self.logger.debug('Looking to destroy apigateway name = "{}" id "{}" in "{}"'.format(self.inputargs.get("name"),
                                                                                             self.inputargs.get("id"),
                                                                                             self.aws_default_region))

        _results = self.exists(convert_to_json=False,**self.inputargs)

        if not _results.get("status"):
            output = 'apigateway name = "{}" id "{}" in "{}" does not exists'.format(self.inputargs.get("name"),
                                                                                     self.inputargs.get("id"),
                                                                                     self.aws_default_region)
            self.successful_output(output=output)

        if not _results["output"].get("id"):
            failed_message = "Cannot determine cloud id to delete"
            self.cmd_failed(failed_message=failed_message)
      
        cmd = "aws apigateway delete-rest-api --rest-api-id {} --region {}".format(_results["output"]["id"],self.aws_default_region)

        for retry in range(0,3):
            results = self.execute(cmd,convert_to_json=None)
            if results.get("status") is True: 
                self.logger.debug('apigateway id "{}" deleted'.format(_results["output"]["id"]))
                self.successful_output(output=results["output"])
            sleep(1)

        failed_message = "could not delete apigateway id {} in {}".format(_results["output"]["id"],self.aws_default_region)
        self.cmd_failed(failed_message=failed_message)

def usage():

    print """
script + environmental variables

or

script + json_input (as argument)

environmental variables:
    basic:
        AWS_ACCESS_KEY_ID  
        AWS_SECRET_ACCESS_KEY
        METHOD
        AWS_DEFAULT_REGION (optional)

    create:
        NAME

    destroy:
        ID or NAME

    get:
        ID (optional)
        NAME (optional)

       """
    exit(4)

if __name__ == '__main__':

    try:
        json_input = sys.argv[1]
    except:
        json_input = None

    main = Main()

    if json_input:
        main.set_inputargs(json_input=json_input)
    else:
        set_env_vars = [ "method",
                         "name",
                         "aws_default_region",
                         "description",
                         "endpoint_configuration",
                         "id" ]

        main.set_inputargs(set_env_vars=set_env_vars)
   
    method = main.inputargs.get("method")

    if not method:
        print "method/ENV VARIABLE METHOD is needed"
        exit(4)

    # Set class and region
    main.get_region()

    if method == "create":

        main.check_required_inputargs(keys=["name"])
        main.create()

    elif method == "destroy":
    
        main.check_either_inputargs(keys=["name","id"])
        main.destroy()

    elif method == "get":

        main.get()

    else:
        usage()
        print 'method "{}" not supported!'.format(method)
        exit(4)
