#!/usr/bin/env python
#
#This file is part of "jiffy".
#
#Project: jiffy: A product for building and managing infrastructure: 
#cloud provider services, and servers and their configurations.
#
#Description: A product for building and managing infrastructure. 
#This includes third party API calls for services such as virtual
#cloud servers, load balancers, databases, and other. The product 
#manages connectivity and appropriate communication among these 
#aws.
#
#Copyright (C) Gary Leong - All Rights Reserved
#Unauthorized copying of this file, via any medium is strictly prohibited
#Proprietary and confidential
#Written by Gary Leong  <gwleong@gmail.com, September 17,2015

import os
import json
import sys
from time import sleep

from ed_helper_publisher.loggerly import ElasticDevLogger
from ed_helper_publisher.cloud.awscli import AwsCli
from ed_helper_publisher.utilities import convert_str2json

class Main(AwsCli):

    def __init__(self,**kwargs):

        AwsCli.__init__(self)
        self.classname = 'Ec2Server'
        self.logger = ElasticDevLogger(self.classname,logcategory="cloudprovider")
        self.logger.debug("Instantiating %s" % self.classname)
        self.base_cmd = "aws ec2"
        self.product = "ec2"
        self.provider = "ec2"
        self.resource_type = "server"
        self.shelloutconfig = "elasticdev:::aws::ec2_server"

    def exists(self,**kwargs):

        #aws ec2 describe-instances --filters "Name=tag:Name,Values=test,Name=instance-state-name,Values=pending,running,shutting-down,stopping,stopped,terminated" --region us-east-1 

        add_cmd = "describe-instances"
        verify_terminate = kwargs.get("verify_terminate")

        name = kwargs.get("name")
        instance_id = kwargs.get("instance_id")
        convert_to_json = kwargs.get("convert_to_json",True)

        if instance_id:
            _cmd = "{} {} --instance-ids {} --filters".format(self.base_cmd,add_cmd,instance_id)
        else:
            _cmd = "{} {} --filters 'Name=tag:Name,Values={}'".format(self.base_cmd,add_cmd,name)

        results = {"status":True}

        if verify_terminate: 
            _cmd = _cmd + " 'Name=instance-state-name,Values=terminated'"
        else:
            # We only get non-terminated instances
            _cmd = _cmd + " 'Name=instance-state-name,Values=pending,running,shutting-down,stopping,stopped'"

        cmd = self.get_cmd_region(_cmd)
        results = self.execute(cmd,convert_to_json=convert_to_json,exit_error=False)
        
        try:
            reservations = results["output"]["Reservations"]
        except:
            reservations = None

        if not reservations: results["status"] = False

        return results

    def get(self):

        results = self.exists(**self.inputargs)

        if results.get("status") is None: exit(0)

        if results.get("status") is False: 
            self.cmd_failed(**self.inputargs)

        self.successful_output(output=results)

    def _get_file_config(self,**kwargs):

        disksize = self.inputargs.get("disksize",20)
        volume_type = self.inputargs.get("volume_type","standard")

        file_config = {"DeviceName":"/dev/sda1"}
        file_config["Ebs"] = {}
        file_config["Ebs"]["DeleteOnTermination"] = True
        file_config["Ebs"]["VolumeSize"] = int(disksize)
        file_config["Ebs"]["VolumeType"] = str(volume_type)

        self.file_config = [ file_config ]

        return self.file_config

    def start(self):

        #aws ec2 start-instances --instance-ids i-5c8282ed

        reservations = self.exists(convert_to_json=True,**self.inputargs)["output"].get("Reservations")

        if len(reservations[0]['Instances']) != 1:
            msg = 'Expected one instance, but found "{}" instances'.format(len(reservations[0]['Instances']))
            self.logger.error(msg)
            exit(9)

        Instance = reservations[0]['Instances'][0]
        instance_id = Instance['InstanceId']

        if Instance['State']['Name'] in [ "shutting-down", "stopping", "stopped" ]:
            self.logger.debug('current status of instance {} is {}"'.format(instance_id,Instance['State']['Name']))
            add_cmd = "start-instances"
            cmd = "{} {} --instance-ids {}".format(self.base_cmd,add_cmd,instance_id)
            self.execute(cmd,convert_to_json=True,exit_error=False)

        Instance = self.exists(convert_to_json=True,**self.inputargs)["output"].get("Reservations")[0]['Instances'][0]
        status = Instance['State']['Name']
        self.logger.debug('current status of instance {} is {}"'.format(instance_id,status))

        _Instance = self.confirm_status(statuses=["running"])
        if _Instance: Instance = _Instance

        # Zero out ip changes since they may/will change when it is started up again
        resource = {"status":"running"}
        resource['private_dns_name'] = Instance["PrivateDnsName"]
        resource['private_ip'] = Instance["PrivateIpAddress"]
        if Instance.get("PublicIpAddress"): resource['public_ip'] = Instance["PublicIpAddress"]
        if Instance.get("PublicDnsName"): resource['public_dns_name'] = Instance["PublicDnsName"]

        self.successful_output(output=resource)

    def stop(self):

        #aws ec2 stop-instances --instance-ids i-5c8282ed

        reservations = self.exists(convert_to_json=True,**self.inputargs)["output"].get("Reservations")

        if len(reservations[0]['Instances']) != 1:
            msg = 'Expected one instance, but found "{}" instances'.format(len(reservations[0]['Instances']))
            self.logger.error(msg)
            exit(9)

        Instance = reservations[0]['Instances'][0]
        instance_id = Instance['InstanceId']

        if Instance['State']['Name'] not in [ "shutting-down", "stopping", "stopped" ]:
            self.logger.debug('current status of instance {} is {}"'.format(instance_id,Instance['State']['Name']))
            add_cmd = "stop-instances"
            cmd = "{} {} --instance-ids {}".format(self.base_cmd,add_cmd,instance_id)
            self.execute(cmd,convert_to_json=True,exit_error=False)

        status = self.exists(convert_to_json=True,**self.inputargs)["output"].get("Reservations")[0]['Instances'][0]['State']['Name']
        self.logger.debug('current status of instance {} is {}"'.format(instance_id,status))

        resource = {"status":"stopped"}

        if self.inputargs.get("confirm",True):
            #_Instance = self.confirm_status(statuses=[ "stopping", "stopped" ])
            # To make sure the server is stopped, we wait unti is confirmed, rather than 
            # confirm it is the process of stopping.
            _Instance = self.confirm_status(statuses=[ "stopped" ])
            if _Instance: Instance = _Instance
            # Zero out ip changes since they may/will change when it is started up again
            resource['private_dns_name'] = Instance.get("PrivateDnsName")
            resource['private_ip'] = Instance.get("PrivateIpAddress")
            #resource['public_ip'] = Instance.get("PublicIpAddress")
            #resource['public_dns_name'] = Instance.get("PublicDnsName")

        # These should be zero-ed out
        resource['public_ip'] = None
        resource['public_dns_name'] = None

        self.successful_output(output=resource)

    def confirm_status(self,statuses=["running"]):

        for count in range(1,30):

            reservations = self.exists(convert_to_json=True,**self.inputargs)["output"].get("Reservations")

            if not reservations: 
                self.logger.debug("Waiting for server to run ...")
                sleep(5)
                continue

            Instance = reservations[0]['Instances'][0]

            _status = Instance["State"]["Name"]
            if _status in statuses: return Instance
            self.logger.debug("Waiting for server to run ...")
            sleep(5)

        Instance = reservations[0]['Instances'][0]
        self.logger.warn('Could not confirm instance "{}" is running. State is "{}"'.format(Instance['InstanceId'],Instance['State']['Name']))

        return False

    def create(self):

        #aws ec2 run-instances --image-id ami-xxxxxxxx --count 1 --instance-type t2.micro --key-name MyKeyPair --security-group-ids sg-903004f8 --subnet-id subnet-6e7f829e
        #aws ec2 run-instances --image-id ami-abc12345 --count 1 \
        #        --instance-type t2.micro --key-name MyKeyPair \
        #        --subnet-id subnet-6e7f829e \
        #        --tag-specifications 'ResourceType=instance,Tags=[{Key=webserver,Value=production}]' 'ResourceType=volume,Tags=[{Key=cost-center,Value=cc123}]' 
        #        --block-device-mappings 'DeviceName=/dev/sda1,Ebs={DeleteOnTermination=true,VolumeSize=32,VolumeType=standard}'

        name = self.inputargs["name"]
        ami = self.inputargs["ami"]
        instance_type = self.inputargs.get("instance_type","t2.micro")
        key = self.inputargs.get("key","ed_ssh_key")
        add_tags = self.inputargs.get("tags")
        security_groups_ids = self.inputargs.get("security_groups_ids")
        security_groups = self.inputargs.get("security_groups")
        subnet_id = self.inputargs.get("subnet_id")
        confirm = self.inputargs.get("confirm",True)

        # Needs False if it finds the server
        if self.exists(convert_to_json=False,**self.inputargs).get("status") is not False:
            failed_message = "{} name = {} already exists".format(self.product,name)
            self.cmd_failed(failed_message=failed_message)

        add_cmd = "run-instances"
        _cmd = "{} {} --image-id {} --instance-type {} --key-name {}".format(self.base_cmd,
                                                                             add_cmd,
                                                                             ami, 
                                                                             instance_type,
                                                                             key)

        resource_tags = self.get_resource_tags()
        _cmd = "{} --tag-specifications ".format(_cmd)+"'ResourceType=instance"+",Tags="+resource_tags+"'"

        if security_groups_ids: _cmd = "{} --security-group-ids {}".format(_cmd,security_groups_ids)
        if security_groups: _cmd = "{} --security-groups {}".format(_cmd,security_groups)

        # We automatically assign it a public ip address
        if subnet_id: _cmd = "{} --subnet-id {} --associate-public-ip-address".format(_cmd,subnet_id)

        self.set_ondisktmp()
        self._get_file_config(**self.inputargs)
        self.file_config_loc = os.path.join(self.tempdir.get(),name)
        self.write_file_config()

        _cmd = "{} --block-device-mappings file://{}".format(_cmd,self.file_config_loc)
        cmd = self.get_cmd_region(_cmd)

        Instance = self.execute(cmd,convert_to_json=True,exit_error=True)["output"]['Instances'][0]
        self.inputargs["instance_id"] = Instance["InstanceId"]

        self.tempdir.delete()

        self.logger.debug("Sleep 5 secs. Waiting for server to run ...")
        sleep(5)

        _Instance = self.confirm_status(statuses=["running"])
        if _Instance: Instance = _Instance

        resource = {"raw":{}}
        resource["raw"][self.product] = Instance
        resource['name'] = name
        resource['hostname'] = name

        resource['instance_id'] = Instance['InstanceId']
        resource['_id'] = Instance['InstanceId']
        resource['id'] = Instance['InstanceId']

        resource['private_dns_name'] = Instance["PrivateDnsName"]
        resource['private_ip'] = Instance["PrivateIpAddress"]

        if Instance.get("PublicIpAddress"): resource['public_ip'] = Instance["PublicIpAddress"]
        if Instance.get("PublicDnsName"): resource['public_dns_name'] = Instance["PublicDnsName"]

        resource['security_groups'] = Instance["SecurityGroups"]
        resource['security_groups_ids'] = Instance["SecurityGroups"]
        resource['security-groups-ids'] = Instance["SecurityGroups"]
        resource['sg_ids'] = Instance["SecurityGroups"]

        if len(Instance["SecurityGroups"]) == 1: 
            resource['security_group'] = Instance["SecurityGroups"][0]
            resource['security_group_id'] = Instance["SecurityGroups"][0]
            resource['security-group-id'] = Instance["SecurityGroups"][0]
            resource['sg_id'] = Instance["SecurityGroups"][0]

        resource['key'] = Instance["KeyName"]
        resource['key_name'] = Instance["KeyName"]
        resource["subnet_id"] = Instance['SubnetId']
        resource["vpc_id"] = Instance['VpcId']
        resource["image_id"] = Instance['ImageId']
        resource["ami"] = Instance['ImageId']
        resource['placement'] = Instance["Placement"]["AvailabilityZone"]
        resource["resource_type"] = self.resource_type
        resource["provider"] = self.provider
        resource["region"] = self.aws_default_region
        resource["aws_default_region"] = self.aws_default_region
        resource['shelloutconfig'] = self.shelloutconfig
        #resource['status'] = Instance['State']['Name']
        resource['status'] = "running"
        resource["active"] = True

        tags = self.get_tags()
        tags.extend( [ Instance['InstanceId'], Instance["Placement"]["AvailabilityZone"] ])

        if add_tags:
            add_tags = convert_str2json(add_tags)
            tags.append(add_tags)

        # Make sure tags are distinct
        resource["tags"] = list(set(tags))

        # Add modify actions stop and start
        resource["modify"] = {}
        resource["modify"]["stop"] = {"shelloutconfig":self.shelloutconfig}
        resource["modify"]["stop"]["insert_env_vars"] = json.dumps(["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"])
        resource["modify"]["stop"]["env_vars"] = json.dumps({"NAME":name,"INSTANCE_ID":Instance['InstanceId'],"METHOD":"stop","AWS_DEFAULT_REGION":self.aws_default_region})

        resource["modify"]["start"] = {"shelloutconfig":self.shelloutconfig}
        resource["modify"]["start"]["insert_env_vars"] = json.dumps(["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"])
        resource["modify"]["start"]["env_vars"] = json.dumps({"NAME":name,"INSTANCE_ID":Instance['InstanceId'],"METHOD":"start","AWS_DEFAULT_REGION":self.aws_default_region})

        # Destroy is special and is at the root level
        resource["destroy"] = {"shelloutconfig":self.shelloutconfig}
        resource["destroy"]["insert_env_vars"] = json.dumps(["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"])
        resource["destroy"]["env_vars"] = json.dumps({"NAME":name,"CONFIRM":confirm,"INSTANCE_ID":Instance['InstanceId'],"METHOD":"destroy","AWS_DEFAULT_REGION":self.aws_default_region})

        self.successful_output(output=resource)

    def confirm_destroy(self):

        for count in range(1,30):

            reservations = self.exists(convert_to_json=True,**self.inputargs)["output"].get("Reservations")
            if not reservations: 
                self.logger.debug("Instance does not exists")
                return True

            reservations = self.exists(convert_to_json=True,verify_terminate=True,**self.inputargs)["output"].get("Reservations")

            if reservations: 
                self.logger.debug("Instance has been confirm terminated")
                return True

            self.logger.debug("Waiting for server to terminate ...")
            sleep(5)
            
        return False

    def destroy(self):

        #aws ec2 terminate-instances --instance-ids i-5203422c

        confirm = self.inputargs.get("confirm",True)
        instance_id = self.inputargs["instance_id"]

        self.logger.debug('Looking to destroy {} instance_id = "{}" in "{}"'.format(self.product,
                                                                                    instance_id,
                                                                                    self.aws_default_region))

        _results = self.exists(convert_to_json=False,**self.inputargs)

        if not _results.get("status"):
            output = '{} instance_id = "{}" in "{}" does not exists'.format(self.product,
                                                                            self.inputargs.get("instance_id"),
                                                                            self.aws_default_region)
            self.successful_output(output=output)

        add_cmd = "terminate-instances"
        _cmd = "{} {} --instance-ids {}".format(self.base_cmd,add_cmd,instance_id)
        cmd = self.get_cmd_region(_cmd)

        results = self.execute(cmd,convert_to_json=None)

        if results.get("status") is True: 

            if confirm and not self.confirm_destroy(): 
                self.logger.warn('Could not confirm destroy of instance_id "{}"'.format(instance_id))
                return False

            self.logger.debug('{} instance_id "{}" destroyed in {}'.format(self.product,instance_id,self.aws_default_region))

            self.successful_output(output=results["output"])

        sleep(1)

        failed_message = "could not destroyed {} instance_id {} in {}".format(self.product,instance_id,self.aws_default_region)
        self.cmd_failed(failed_message=failed_message)

def usage():

    print """
script + environmental variables

or

script + json_input (as argument)

environmental variables:
    basic:
        AWS_ACCESS_KEY_ID  
        AWS_SECRET_ACCESS_KEY
        METHOD
        AWS_DEFAULT_REGION (optional)

    stop:
        INSTANCE_ID

    start:
        INSTANCE_ID

    create:
        NAME
        AMI 
        INSTANCE_TYPE (default - t2.micro)
        INSTANCE_ID (optional)
        KEY (optional)
        SECURITY_GROUPS_IDS (optional)
        SECURITY_GROUPS (optional)
        SUBNET_ID (optional)
        DISKSIZE (optional)
        VOLUME_TYPE (optional)
        JOB_INSTANCE_ID (optional)
        SCHEDULE_ID (optional)
        TAGS (optional)

    destroy:
        INSTANCE_ID
        CONFIRM

    get:
        NAME

       """
    exit(4)

if __name__ == '__main__':

    try:
        json_input = sys.argv[1]
    except:
        json_input = None

    main = Main()

    if json_input:
        main.set_inputargs(json_input=json_input)
    else:
        set_env_vars = [ "method",
                         "name",
                         "disksize",
                         "ami",
                         "job_instance_id",
                         "schedule_id",
                         "instance_id",
                         "instance_type",
                         "key",
                         "security_groups_ids",
                         "security_groups",
                         "confirm",
                         "subnet_id",
                         "volume_type",
                         "tags",
                         "aws_default_region" ]

        main.set_inputargs(set_env_vars=set_env_vars)
   
    method = main.inputargs.get("method")

    if not method:
        print "method/ENV VARIABLE METHOD is needed"
        exit(4)

    # Set class and region
    main.get_region()

    if method == "create":

        req_keys = [ "name",
                     "ami",
                     "key" ]

        main.check_required_inputargs(keys=req_keys)
        main.create()

    elif method == "start":

        req_keys = [ "instance_id" ]
        main.check_required_inputargs(keys=req_keys)
        main.start()

    elif method == "stop":

        req_keys = [ "instance_id" ]
        main.check_required_inputargs(keys=req_keys)
        main.stop()

    elif method == "destroy":
    
        main.check_required_inputargs(keys=["instance_id"])
        main.destroy()

    elif method == "get":

        main.check_required_inputargs(keys=["name"])
        main.get()

    else:
        usage()
        print 'method "{}" not supported!'.format(method)
        exit(4)




